# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       kde5-kfilemetadata
Summary:    Library for extracting file metadata
Version:    4.97.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kde5-kfilemetadata.yaml
Source101:  kde5-kfilemetadata-rpmlintrc
Requires:   kde5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  pkgconfig(taglib)
BuildRequires:  kde5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kf5-umbrella
BuildRequires:  kf5-ki18n-devel
BuildRequires:  kf5-kservice-devel
BuildRequires:  kf5-karchive-devel


%description
Library for extracting file metadata



%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kf5-ki18n-devel
Requires:   kf5-kservice-devel
Requires:   kf5-karchive-devel

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.



%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kde5_make
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
%kde5_make_install
# << install pre

# >> install post
# << install post









%files
%defattr(-,root,root,-)
%doc COPYING.LGPL*
%{_kde5_libdir}/libkfilemetadata.so.*
%{_kde5_plugindir}/kfilemetadata_*.so
%{_kde5_datadir}/kservices5
%{_kde5_datadir}/kservicetypes5/
# >> files
# << files


%files devel
%defattr(-,root,root,-)
%{_kde5_libdir}/libkfilemetadata.so
%{_kde5_libdir}/cmake/KFileMetaData
%{_includedir}/kfilemetadata
# >> files devel
# << files devel

